// Filename: src/constants/FeatureNames.ts

/**
 * --- FEATURES ---
 * Defines all analytical output Views generated by the system. These are the cache keys.
 * Each Feature represents a consolidated data view for a major application section.
 */
export const ALL_FEATURE_NAMES = [
  // 1. Dominance Views (Consolidated Analytics)
  "CURRENT_DOMINANCE", // Current dominance for BTC, ETH, stablecoins, and others.
  "DOMINANCE_VIEW_90D", // Complete data for the Dominance Trends/Shifts widget (90 days).
  "DOMINANCE_TOP_10_CONC", // Data showing concentration of dominance in top 10 coins.
  "DOMINANCE_HEATMAP_DATA", // Time-series data used to generate a correlation/dominance heatmap.

  // 2. Volatility (TTL Driver - Bundled)
  "CURRENT_VOLATILITY", // Contains 1H and 24H volatility scores and the mapped levels.

  // 3. Sector, Correlation, & Context
  "SECTOR_DOMINANCE_CURRENT", // Current dominance for defined sectors (e.g., DeFi, L2).
  "CORRELATION_MATRIX_FULL", // Complete matrix of coin-to-coin correlation data.
  "HISTORICAL_CONTEXT_OVERLAY", // Long-term data for general trend overlays.
  "PREDICTIVE_SIGNAL_1D", // Short-term predictive output.

  // 4. Raw Data Cache Keys (Used internally)
  "RAW_MARKETS_TOP_50", // Raw, unprocessed market data for the top 50 coins.
] as const;

export type FeatureName = (typeof ALL_FEATURE_NAMES)[number];
